name: Pull Request to Upstream main

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  packer_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Packer Init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: aws-linux2.pkr.hcl
          working_directory: packer
        env:
          PACKER_LOG: 1

      - name: Packer Build
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: -var=aws_access_key_id=${{secrets.AWS_ACCESS_KEY_ID}} -var=aws_secret_access_key=${{secrets.AWS_SECRET_ACCESS_KEY}} -var-file=values.auto.pkvars.hcl -color=false -on-error=abort
          target: aws-linux2.pkr.hcl
          working_directory: packer
        env:
          PACKER_LOG: 1

      - name: Confirm Project run
        run: echo "End"